### ISSUE TITLE
Change to use OkHttp instead of TubeSock

### ISSUE THREAD

**Issue by rogerhu** [ParsePlatform/ParseLiveQuery-Android#13]
TubeSockWebSocketClient library is being used.   We should just standardize on OkHttp v3.6.0 (and possibly share instances between Parse/Parse Live Query?)  One advantage is that we can use ParseLogHttpInterceptor to troubleshoot network requests.

**Comment by rogerhu** [comment]
https://github.com/ParsePlatform/ParseLiveQuery-Android/pull/19

**Comment by jhansche** [comment]
This may actually solve another problem I'm having, related to getting it to use the configured proxy server.  Apparently TubeSock does not support the configured HTTP proxy, which makes it difficult to use with tools like Charles proxy.

OkHttp appears to use the system proxy automatically, so that would be helpful.  @rogerhu is this something that we can test in our applications using the latest snapshots, or would we have to manually create the OkHttp websocket client in order to test it?

**Comment by jhansche** [comment]
Looks like we can create a class in the com.parse package to hoist access to the `ParseLiveQueryClientImpl` constructor that takes a WebSocketClientFactory.  Would be nice to make that a bit more accessible.  I.e., by allowing a way to inject the default client factory instance, so that existing uses of `ParseLiveQueryClient.getClient()` will automatically use the injected websocket factory.

**Comment by rogerhu** [comment]
I'm going to change now.  I really don't think we should be using TubeSocket especially since it is using the old Apache HttpClient which is no longer being supported by Android.

**Comment by rogerhu** [comment]
https://github.com/ParsePlatform/ParseLiveQuery-Android/pull/28/files

**Comment by jhansche** [comment]
Added with #19; and tubesock removed with #28. Closing
